services:

  web:
    build: .

    container_name: rentify_web

    command: python manage.py runserver 0.0.0.0:8000

    ports:
      - "8000:8000"

    env_file:
      - .env

    volumes:
      - .:/app
      - static_data:/app/staticfiles
      - media_data:/app/media

    restart: unless-stopped


volumes:
  static_data:
  media_data: