# Generated by Django 5.2.15 on 2026-07-19 22:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_alter_property_owner_alter_property_price_per_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='price_per_night',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
