# Generated by Django 5.2.15 on 2026-07-19 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_property_price_per_night'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='price_per_month',
        ),
    ]
